openapi: 3.0.0
info:
  title: Express_shipment
  version: 1.0.0
servers:
  - url: http://{{host}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /express-shipment/business-partners:
    get:
      tags:
        - default
      summary: ListBusinessPartners
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Wed, 06 Mar 2024 20:35:33 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '768'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '144'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '6'
                records:
                  - id: 117
                    value: C&W
                    tax_id: ''
                    name: C&W Construction
                    description: ''
                  - id: 118
                    value: JoeBlock
                    tax_id: ''
                    name: Joe Block
                    description: ''
                  - id: 119
                    value: GardenUser
                    tax_id: ''
                    name: GardenUser BP
                    description: ''
                  - id: 121
                    value: Patio
                    tax_id: ''
                    name: Patio Fun, Inc.
                    description: ''
                  - id: 120
                    value: SeedFarm
                    tax_id: ''
                    name: Seed Farm Inc.
                    description: Customer & Vendor
                  - id: 112
                    value: Standard
                    tax_id: ''
                    name: Standard
                    description: Walk-In Customer
                next_page_token: ''
  /express-shipment/orders:
    get:
      tags:
        - default
      summary: ListSalesOrders
      description: |-
        ### Request Params

        - business_partner_id (int32, required)
      security:
        - bearerAuth: []
      parameters:
        - name: business_partner_id
          in: query
          schema:
            type: integer
          example: '50001'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Fri, 08 Mar 2024 18:41:36 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '65'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '68'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '0'
                records: []
                next_page_token: ''
  /express-shipment/products:
    get:
      tags:
        - default
      summary: ListProductsRequest
      description: |-
        ### Request Params

        - order_id (int32, required)
      security:
        - bearerAuth: []
      parameters:
        - name: order_id
          in: query
          schema:
            type: integer
          example: '100'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Fri, 08 Mar 2024 13:58:22 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '187'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '125'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '1'
                records:
                  - id: 130
                    upc: ''
                    sku: ''
                    value: Plum Tree
                    name: Plum Tree
                    description: ''
                next_page_token: ''
  /express-shipment/shipments:
    post:
      tags:
        - default
      summary: CreateShipment
      description: |-
        ### Request Body

        - order_id (int32,required)
            
        - is_create_lines_from_order(bool)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                order_id: 100
                is_create_lines_from_order: true
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Fri, 08 Mar 2024 13:54:25 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '170'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '141'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                id: 1000000
                document_no: '600004'
                date_ordered: '2021-01-22T04:00:00Z'
                movement_date: '2024-03-08T04:00:00Z'
                order_id: 100
                is_completed: false
  /express-shipment/shipments/{id}:
    delete:
      tags:
        - default
      summary: DeleteShipment
      description: |-
        ### Request Params

        - id (int32,required)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1000000'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Fri, 08 Mar 2024 13:54:54 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '3'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '95'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example: {}
  /express-shipment/shipments/{id}/process:
    post:
      tags:
        - default
      summary: ProcessShipment
      description: |-
        ### Request Params

        - id (int32,required)
            

        ### Request Body

        - description (String)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                description: prueba
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '100'
      responses:
        '500':
          description: Internal Server Error
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Fri, 08 Mar 2024 13:57:24 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '74'
            Connection:
              schema:
                type: string
                example: keep-alive
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '106'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                code: 13
                message: Entrega / Recibo Procesado
                details: []
  /express-shipment/shipments/{shipment_id}/lines:
    post:
      tags:
        - default
      summary: CreateShipmentLine
      description: |-
        ### Request Params

        - shipment_id (int32,required)
            

        ### Request Body

        - description (String)
        - product_id (int32, required)
        - quantity (int32)
            
        - is_quantity_from_order_line (bool)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                description: prueba
                product_id: 120
                quantity: '4'
                is_quantity_from_order_line: true
      security:
        - bearerAuth: []
      parameters:
        - name: shipment_id
          in: path
          schema:
            type: integer
          required: true
          example: '100'
      responses:
        '500':
          description: Internal Server Error
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Fri, 08 Mar 2024 13:49:04 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '74'
            Connection:
              schema:
                type: string
                example: keep-alive
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '144'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                code: 13
                message: Entrega / Recibo Procesado
                details: []
    get:
      tags:
        - default
      summary: ListShipmentLines
      description: |-
        ### Request Params

        - shipment_id (int32,required)
      security:
        - bearerAuth: []
      parameters:
        - name: shipment_id
          in: path
          schema:
            type: integer
          required: true
          example: '100'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Fri, 08 Mar 2024 13:48:21 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '310'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '142'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '1'
                records:
                  - id: 100
                    order_line_id: 100
                    product:
                      id: 130
                      upc: ''
                      sku: ''
                      value: Plum Tree
                      name: Plum Tree
                      description: ''
                    description: ''
                    quantity: '1'
                    line: 10
                next_page_token: ''
  /express-shipment/shipments/{shipment_id}/lines/{id}:
    delete:
      tags:
        - default
      summary: DeleteShipmentLine
      description: |-
        ### Request Params

        - shipment_id (int32,required)
            
        - id (int32,required)
      security:
        - bearerAuth: []
      parameters:
        - name: shipment_id
          in: path
          schema:
            type: integer
          required: true
          example: '100'
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '100'
      responses:
        '500':
          description: Internal Server Error
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Fri, 08 Mar 2024 13:52:51 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '81'
            Connection:
              schema:
                type: string
                example: keep-alive
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '131'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                code: 13
                message: Línea Entrega / Recibo Procesado
                details: []
    patch:
      tags:
        - default
      summary: UpdateShipmentLine
      description: |-
        ### Request Params

        - shipment_id (int32,required)
            
        - id (int32,required)
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: shipment_id
          in: path
          schema:
            type: integer
          required: true
          example: '100'
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '100'
      responses:
        '500':
          description: Internal Server Error
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Fri, 08 Mar 2024 13:53:20 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '81'
            Connection:
              schema:
                type: string
                example: keep-alive
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '108'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                code: 13
                message: Línea Entrega / Recibo Procesado
                details: []