openapi: 3.0.0
info:
  title: Payment_allocation
  version: 1.0.0
servers:
  - url: http://{{host}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /payment-allocation/business-partners:
    get:
      tags:
        - default
      summary: ListBusinessPartners
      description: >-
        **Endpoint**: GET /payment_allocation


        **Description**: Returns ListLookupItems


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/payment-allocation/business-partners


        **Method**: GET


        **Application Example**


        ``` bash

        curl --location
        'http://api.adempiere.io/payment-allocation/business-partners' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTU0IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDAsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzEwNzE1NzAxLCJleHAiOjE3MTA4MDIxMDF9.sdizIymo1Yd8P8w4D4ORu2EfavUfgxsPPfQIJMNJQQ8'

         ```

        **Example Answer**


        ``` json

        {
                    "id": 50003,
                    "table_name": "C_BPartner",
                    "values": {
                        "KeyColumn": 50003,
                        "DisplayColumn": "Chemical Product, inc",
                        "UUID": "b14b6c53-ca82-4dbc-841a-640b04de76bb"
                    },
                    "is_active": true
                },

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 14:30:17 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '3610'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '91'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '17'
                records:
                  - id: 50003
                    table_name: C_BPartner
                    values:
                      KeyColumn: 50003
                      DisplayColumn: Chemical Product, inc
                      UUID: b14b6c53-ca82-4dbc-841a-640b04de76bb
                    is_active: true
                  - id: 50002
                    table_name: C_BPartner
                    values:
                      KeyColumn: 50002
                      DisplayColumn: Chrome, Inc
                      UUID: f472cd49-4f19-4fc3-856a-cb9038cf2924
                    is_active: true
                  - id: 50001
                    table_name: C_BPartner
                    values:
                      KeyColumn: 50001
                      DisplayColumn: Color, Inc
                      UUID: 5e616d3e-c55b-4ede-9b0e-ac3ae834556b
                    is_active: true
                  - id: 117
                    table_name: C_BPartner
                    values:
                      KeyColumn: 117
                      DisplayColumn: C&W Construction
                      UUID: b7bafd8e-ae3b-4bbc-9a0d-d47fdbef390f
                    is_active: true
                  - id: 113
                    table_name: C_BPartner
                    values:
                      KeyColumn: 113
                      DisplayColumn: GardenAdmin BP
                      UUID: d430bdde-e5e4-476b-8dc9-4b0b5d5b02cc
                    is_active: true
                  - id: 119
                    table_name: C_BPartner
                    values:
                      KeyColumn: 119
                      DisplayColumn: GardenUser BP
                      UUID: 0b870ceb-a34f-4876-8225-0053f11385d2
                    is_active: true
                  - id: 118
                    table_name: C_BPartner
                    values:
                      KeyColumn: 118
                      DisplayColumn: Joe Block
                      UUID: c3cfeb5f-1b2f-4f4b-a16c-d9cda23f59e1
                    is_active: true
                  - id: 121
                    table_name: C_BPartner
                    values:
                      KeyColumn: 121
                      DisplayColumn: Patio Fun, Inc.
                      UUID: ca5b584a-c9e8-448f-a388-8ac7c0f02501
                    is_active: true
                  - id: 120
                    table_name: C_BPartner
                    values:
                      KeyColumn: 120
                      DisplayColumn: Seed Farm Inc.
                      UUID: 2ad2a623-3d1f-47f4-969a-f44f7a05481f
                    is_active: true
                  - id: 112
                    table_name: C_BPartner
                    values:
                      KeyColumn: 112
                      DisplayColumn: Standard
                      UUID: f5388c95-7424-447d-85de-91424f9da147
                    is_active: true
                  - id: 50004
                    table_name: C_BPartner
                    values:
                      KeyColumn: 50004
                      DisplayColumn: Store Central
                      UUID: 8b894863-afbe-4384-a8ed-bf0325a5ec25
                    is_active: true
                  - id: 50005
                    table_name: C_BPartner
                    values:
                      KeyColumn: 50005
                      DisplayColumn: Store East
                      UUID: c6c2de1e-2f0f-4ef8-b7f3-29d80d0cfdb8
                    is_active: true
                  - id: 50007
                    table_name: C_BPartner
                    values:
                      KeyColumn: 50007
                      DisplayColumn: Store North
                      UUID: 01c65f4b-272c-4fb6-b12a-089d207cadb8
                    is_active: true
                  - id: 50008
                    table_name: C_BPartner
                    values:
                      KeyColumn: 50008
                      DisplayColumn: Store South
                      UUID: 88f0d79e-bc97-447d-8245-91bd79c0dcf7
                    is_active: true
                  - id: 50009
                    table_name: C_BPartner
                    values:
                      KeyColumn: 50009
                      DisplayColumn: Store West
                      UUID: b419cad9-bb5b-4a2f-bbdb-1c3c70657408
                    is_active: true
                  - id: 114
                    table_name: C_BPartner
                    values:
                      KeyColumn: 114
                      DisplayColumn: Tree Farm Inc.
                      UUID: 254e660c-4863-460a-8a69-2b75f6461a33
                    is_active: true
                  - id: 50000
                    table_name: C_BPartner
                    values:
                      KeyColumn: 50000
                      DisplayColumn: Wood, Inc
                      UUID: 2d96ae84-d50e-447a-bdb7-496242fd846f
                    is_active: true
                next_page_token: ''
  /payment-allocation/organizations:
    get:
      tags:
        - default
      summary: ListOrganizations
      description: >-
        **Endpoint**: GET /payment_allocation


        **Description**: Returns ListLookupItems


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/payment-allocation/organizations


        **Method**: GET


        **Application Example**


        ``` bash

        curl --location
        'http://api.adempiere.io/payment-allocation/organizations' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTU0IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDAsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzEwNzE1NzAxLCJleHAiOjE3MTA4MDIxMDF9.sdizIymo1Yd8P8w4D4ORu2EfavUfgxsPPfQIJMNJQQ8'

         ```

        **Example Answer**


        ``` json

        {
                    "id": 0,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 0,
                        "DisplayColumn": "*",
                        "UUID": "a3e5c878-fb40-11e8-a479-7a0060f0aa01"
                    },
                    "is_active": true
                },

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 14:30:57 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '1869'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '95'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '9'
                records:
                  - id: 0
                    table_name: AD_Org
                    values:
                      KeyColumn: 0
                      DisplayColumn: '*'
                      UUID: a3e5c878-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 50001
                    table_name: AD_Org
                    values:
                      KeyColumn: 50001
                      DisplayColumn: Fertilizer
                      UUID: 5bdf61e6-18d5-491e-8826-ae7a9557e635
                    is_active: true
                  - id: 50000
                    table_name: AD_Org
                    values:
                      KeyColumn: 50000
                      DisplayColumn: Furniture
                      UUID: 803a37b7-0cee-4411-99aa-d3b328dec3b1
                    is_active: true
                  - id: 11
                    table_name: AD_Org
                    values:
                      KeyColumn: 11
                      DisplayColumn: HQ
                      UUID: 08c224db-bb86-4306-9fa5-ba1dfd34b693
                    is_active: true
                  - id: 12
                    table_name: AD_Org
                    values:
                      KeyColumn: 12
                      DisplayColumn: Store Central
                      UUID: 6a0e31b1-2ade-4f8e-a907-ed63ab29fc0d
                    is_active: true
                  - id: 50005
                    table_name: AD_Org
                    values:
                      KeyColumn: 50005
                      DisplayColumn: Store East
                      UUID: 818cfb05-f9db-4a1c-853f-7b3f2b35337a
                    is_active: true
                  - id: 50002
                    table_name: AD_Org
                    values:
                      KeyColumn: 50002
                      DisplayColumn: Store North
                      UUID: 06e23570-6653-4b3c-a921-6c54732b02a9
                    is_active: true
                  - id: 50004
                    table_name: AD_Org
                    values:
                      KeyColumn: 50004
                      DisplayColumn: Store South
                      UUID: cf2ac4a7-0718-4f69-a042-bb8fcb85e9da
                    is_active: true
                  - id: 50006
                    table_name: AD_Org
                    values:
                      KeyColumn: 50006
                      DisplayColumn: Store West
                      UUID: 51748134-e4f9-4d19-b568-77fe15b75887
                    is_active: true
                next_page_token: ''
  /payment-allocation/currencies:
    get:
      tags:
        - default
      summary: ListCurrencies
      description: >-
        **Endpoint**: GET /payment_allocation


        **Description**: Returns ListLookupItems


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/payment-allocation/currencies


        **Method**: GET


        **Application Example**


        ``` bash

        curl --location 'http://api.adempiere.io/payment-allocation/currencies'
        \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTU0IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDAsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzEwNzE1NzAxLCJleHAiOjE3MTA4MDIxMDF9.sdizIymo1Yd8P8w4D4ORu2EfavUfgxsPPfQIJMNJQQ8'

         ```

        **Example Answer**


        ``` json
         {
                    "id": 238,
                    "table_name": "C_Currency",
                    "values": {
                        "KeyColumn": 238,
                        "DisplayColumn": "AED",
                        "UUID": "a5678cc2-fb40-11e8-a479-7a0060f0aa01"
                    },
                    "is_active": true
                },

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 14:31:31 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '9961'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '74'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '177'
                records:
                  - id: 238
                    table_name: C_Currency
                    values:
                      KeyColumn: 238
                      DisplayColumn: AED
                      UUID: a5678cc2-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 195
                    table_name: C_Currency
                    values:
                      KeyColumn: 195
                      DisplayColumn: AFA
                      UUID: a5675e28-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 271
                    table_name: C_Currency
                    values:
                      KeyColumn: 271
                      DisplayColumn: ALL
                      UUID: a567a4aa-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 143
                    table_name: C_Currency
                    values:
                      KeyColumn: 143
                      DisplayColumn: AMD
                      UUID: a567442e-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 284
                    table_name: C_Currency
                    values:
                      KeyColumn: 284
                      DisplayColumn: ANG
                      UUID: a567b454-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 144
                    table_name: C_Currency
                    values:
                      KeyColumn: 144
                      DisplayColumn: AOA
                      UUID: a5674500-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 118
                    table_name: C_Currency
                    values:
                      KeyColumn: 118
                      DisplayColumn: ARS
                      UUID: a56734fc-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 104
                    table_name: C_Currency
                    values:
                      KeyColumn: 104
                      DisplayColumn: ATS
                      UUID: a5671f30-fb40-11e8-a479-7a0060f0aa01
                    is_active: false
                  - id: 120
                    table_name: C_Currency
                    values:
                      KeyColumn: 120
                      DisplayColumn: AUD
                      UUID: a56735a6-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 196
                    table_name: C_Currency
                    values:
                      KeyColumn: 196
                      DisplayColumn: AWG
                      UUID: a5676882-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 145
                    table_name: C_Currency
                    values:
                      KeyColumn: 145
                      DisplayColumn: AZN
                      UUID: a56745aa-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 268
                    table_name: C_Currency
                    values:
                      KeyColumn: 268
                      DisplayColumn: BAM
                      UUID: a567a2e8-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 202
                    table_name: C_Currency
                    values:
                      KeyColumn: 202
                      DisplayColumn: BBD
                      UUID: a5676f8a-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 322
                    table_name: C_Currency
                    values:
                      KeyColumn: 322
                      DisplayColumn: BDT
                      UUID: a56707de-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 105
                    table_name: C_Currency
                    values:
                      KeyColumn: 105
                      DisplayColumn: BEF
                      UUID: a5671fd0-fb40-11e8-a479-7a0060f0aa01
                    is_active: false
                  - id: 279
                    table_name: C_Currency
                    values:
                      KeyColumn: 279
                      DisplayColumn: BGL
                      UUID: a567a95a-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 200
                    table_name: C_Currency
                    values:
                      KeyColumn: 200
                      DisplayColumn: BHD
                      UUID: a5676da0-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 253
                    table_name: C_Currency
                    values:
                      KeyColumn: 253
                      DisplayColumn: BIF
                      UUID: a56791ea-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 201
                    table_name: C_Currency
                    values:
                      KeyColumn: 201
                      DisplayColumn: BMD
                      UUID: a5676ed6-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 198
                    table_name: C_Currency
                    values:
                      KeyColumn: 198
                      DisplayColumn: BND
                      UUID: a5676ba2-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 146
                    table_name: C_Currency
                    values:
                      KeyColumn: 146
                      DisplayColumn: BOB
                      UUID: a567464a-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 297
                    table_name: C_Currency
                    values:
                      KeyColumn: 297
                      DisplayColumn: BRL
                      UUID: a567bbfc-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 199
                    table_name: C_Currency
                    values:
                      KeyColumn: 199
                      DisplayColumn: BSD
                      UUID: a5676d00-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 290
                    table_name: C_Currency
                    values:
                      KeyColumn: 290
                      DisplayColumn: BWP
                      UUID: a567b882-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 203
                    table_name: C_Currency
                    values:
                      KeyColumn: 203
                      DisplayColumn: BYR
                      UUID: a567719c-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 207
                    table_name: C_Currency
                    values:
                      KeyColumn: 207
                      DisplayColumn: BZD
                      UUID: a56777aa-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 116
                    table_name: C_Currency
                    values:
                      KeyColumn: 116
                      DisplayColumn: CAD
                      UUID: a5673164-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 147
                    table_name: C_Currency
                    values:
                      KeyColumn: 147
                      DisplayColumn: CDF
                      UUID: a56746e0-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 318
                    table_name: C_Currency
                    values:
                      KeyColumn: 318
                      DisplayColumn: CHF
                      UUID: a567031a-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 228
                    table_name: C_Currency
                    values:
                      KeyColumn: 228
                      DisplayColumn: CLP
                      UUID: a5677cfa-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 332
                    table_name: C_Currency
                    values:
                      KeyColumn: 332
                      DisplayColumn: CNY
                      UUID: a5670e00-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 230
                    table_name: C_Currency
                    values:
                      KeyColumn: 230
                      DisplayColumn: COP
                      UUID: a5677e26-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 336
                    table_name: C_Currency
                    values:
                      KeyColumn: 336
                      DisplayColumn: CRC
                      UUID: a5671878-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 232
                    table_name: C_Currency
                    values:
                      KeyColumn: 232
                      DisplayColumn: CUP
                      UUID: a56788da-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 210
                    table_name: C_Currency
                    values:
                      KeyColumn: 210
                      DisplayColumn: CVE
                      UUID: a5677a02-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 163
                    table_name: C_Currency
                    values:
                      KeyColumn: 163
                      DisplayColumn: CYP
                      UUID: a5675978-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 148
                    table_name: C_Currency
                    values:
                      KeyColumn: 148
                      DisplayColumn: CZK
                      UUID: a56748d4-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 103
                    table_name: C_Currency
                    values:
                      KeyColumn: 103
                      DisplayColumn: DEM
                      UUID: a5671e90-fb40-11e8-a479-7a0060f0aa01
                    is_active: false
                  - id: 237
                    table_name: C_Currency
                    values:
                      KeyColumn: 237
                      DisplayColumn: DJF
                      UUID: a5678c2c-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 241
                    table_name: C_Currency
                    values:
                      KeyColumn: 241
                      DisplayColumn: DKK
                      UUID: a567901e-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 298
                    table_name: C_Currency
                    values:
                      KeyColumn: 298
                      DisplayColumn: DOP
                      UUID: a567bc9c-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 235
                    table_name: C_Currency
                    values:
                      KeyColumn: 235
                      DisplayColumn: DZD
                      UUID: a5678af6-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 285
                    table_name: C_Currency
                    values:
                      KeyColumn: 285
                      DisplayColumn: EEK
                      UUID: a567b4fe-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 164
                    table_name: C_Currency
                    values:
                      KeyColumn: 164
                      DisplayColumn: EGP
                      UUID: a5675a0e-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 270
                    table_name: C_Currency
                    values:
                      KeyColumn: 270
                      DisplayColumn: ERN
                      UUID: a567a414-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 111
                    table_name: C_Currency
                    values:
                      KeyColumn: 111
                      DisplayColumn: ESP
                      UUID: a5672bd8-fb40-11e8-a479-7a0060f0aa01
                    is_active: false
                  - id: 204
                    table_name: C_Currency
                    values:
                      KeyColumn: 204
                      DisplayColumn: ETB
                      UUID: a567748a-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 102
                    table_name: C_Currency
                    values:
                      KeyColumn: 102
                      DisplayColumn: EUR
                      UUID: a5673830-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 106
                    table_name: C_Currency
                    values:
                      KeyColumn: 106
                      DisplayColumn: FIM
                      UUID: a5672066-fb40-11e8-a479-7a0060f0aa01
                    is_active: false
                  - id: 252
                    table_name: C_Currency
                    values:
                      KeyColumn: 252
                      DisplayColumn: FJD
                      UUID: a5679154-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                next_page_token: 9d1ffadb-c355-420c-9514-bdd5b60b5b27-2
  /payment-allocation/transaction-types:
    get:
      tags:
        - default
      summary: ListTransactionTypes
      description: >-
        **Endpoint**: GET /payment_allocation


        **Description**: Returns ListLookupItems


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/payment-allocation/transaction-types


        **Method**: GET


        **Application Example**


        ``` bash

        curl --location
        'http://api.adempiere.io/payment-allocation/transaction-types' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTU0IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDAsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzEwNzE1NzAxLCJleHAiOjE3MTA4MDIxMDF9.sdizIymo1Yd8P8w4D4ORu2EfavUfgxsPPfQIJMNJQQ8'

         ```

        **Example Answer**


        ``` json

        {
                    "id": 0,
                    "table_name": "AD_Ref_List",
                    "values": {
                        "KeyColumn": "A",
                        "ValueColumn": "A",
                        "DisplayColumn": "CxC & CxP",
                        "UUID": "a456efb2-fb40-11e8-a479-7a0060f0aa01"
                    },
                    "is_active": true
                },

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Fri, 08 Mar 2024 16:32:06 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '744'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '133'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '3'
                records:
                  - id: 0
                    table_name: AD_Ref_List
                    values:
                      KeyColumn: A
                      ValueColumn: A
                      DisplayColumn: CxC & CxP
                      UUID: a456efb2-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 0
                    table_name: AD_Ref_List
                    values:
                      KeyColumn: R
                      ValueColumn: R
                      DisplayColumn: Sólo CxC
                      UUID: a456f016-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                  - id: 0
                    table_name: AD_Ref_List
                    values:
                      KeyColumn: P
                      ValueColumn: P
                      DisplayColumn: Sólo CxP
                      UUID: a456f07a-fb40-11e8-a479-7a0060f0aa01
                    is_active: true
                next_page_token: ''
  /payment-allocation/charges:
    get:
      tags:
        - default
      summary: ListCharges
      description: >-
        **Endpoint**: GET /payment_allocation


        **Description**: Returns ListLookupItems


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/payment-allocation/charges


        **Method**: GET


        **Application Example**


        ``` bash

        curl --location 'http://api.adempiere.io/payment-allocation/charges' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTU0IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDAsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzEwNzE1NzAxLCJleHAiOjE3MTA4MDIxMDF9.sdizIymo1Yd8P8w4D4ORu2EfavUfgxsPPfQIJMNJQQ8'

         ```

        **Example Answer**


        ``` json

        {
                    "id": 100,
                    "table_name": "C_Charge",
                    "values": {
                        "KeyColumn": 100,
                        "DisplayColumn": "Cargo Bancario",
                        "UUID": "f238dfd0-9d73-4eaa-b043-64914c45f59d"
                    },
                    "is_active": true
                },

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 14:42:52 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '712'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '92'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '3'
                records:
                  - id: 100
                    table_name: C_Charge
                    values:
                      KeyColumn: 100
                      DisplayColumn: Cargo Bancario
                      UUID: f238dfd0-9d73-4eaa-b043-64914c45f59d
                    is_active: true
                  - id: 50007
                    table_name: C_Charge
                    values:
                      KeyColumn: 50007
                      DisplayColumn: Cash for Store Central In-Transfer
                      UUID: 6cda9209-98e8-4545-b020-b5e722e711f0
                    is_active: true
                  - id: 101
                    table_name: C_Charge
                    values:
                      KeyColumn: 101
                      DisplayColumn: Comisiones Pagadas
                      UUID: 49af021f-a5bf-459f-aa4b-acec62e80b6a
                    is_active: true
                next_page_token: ''
  /payment-allocation/organizations/transactions:
    get:
      tags:
        - default
      summary: ListTransactionOrganizations
      description: >-
        **Endpoint**: GET /payment_allocation


        **Description**: Returns ListLookupItems


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/payment-allocation/organizations/transactions


        **Method**: GET


        **Application Example**


        ``` bash

        curl --location
        'http://api.adempiere.io/payment-allocation/organizations/transactions'
        \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTU0IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDAsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzEwNzE1NzAxLCJleHAiOjE3MTA4MDIxMDF9.sdizIymo1Yd8P8w4D4ORu2EfavUfgxsPPfQIJMNJQQ8'

         ```

        **Example Answer**


        ``` json

        {
                    "id": 50001,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 50001,
                        "DisplayColumn": "Fertilizer",
                        "UUID": "5bdf61e6-18d5-491e-8826-ae7a9557e635"
                    },
                    "is_active": true
                },

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 14:43:35 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '1682'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '87'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '8'
                records:
                  - id: 50001
                    table_name: AD_Org
                    values:
                      KeyColumn: 50001
                      DisplayColumn: Fertilizer
                      UUID: 5bdf61e6-18d5-491e-8826-ae7a9557e635
                    is_active: true
                  - id: 50000
                    table_name: AD_Org
                    values:
                      KeyColumn: 50000
                      DisplayColumn: Furniture
                      UUID: 803a37b7-0cee-4411-99aa-d3b328dec3b1
                    is_active: true
                  - id: 11
                    table_name: AD_Org
                    values:
                      KeyColumn: 11
                      DisplayColumn: HQ
                      UUID: 08c224db-bb86-4306-9fa5-ba1dfd34b693
                    is_active: true
                  - id: 12
                    table_name: AD_Org
                    values:
                      KeyColumn: 12
                      DisplayColumn: Store Central
                      UUID: 6a0e31b1-2ade-4f8e-a907-ed63ab29fc0d
                    is_active: true
                  - id: 50005
                    table_name: AD_Org
                    values:
                      KeyColumn: 50005
                      DisplayColumn: Store East
                      UUID: 818cfb05-f9db-4a1c-853f-7b3f2b35337a
                    is_active: true
                  - id: 50002
                    table_name: AD_Org
                    values:
                      KeyColumn: 50002
                      DisplayColumn: Store North
                      UUID: 06e23570-6653-4b3c-a921-6c54732b02a9
                    is_active: true
                  - id: 50004
                    table_name: AD_Org
                    values:
                      KeyColumn: 50004
                      DisplayColumn: Store South
                      UUID: cf2ac4a7-0718-4f69-a042-bb8fcb85e9da
                    is_active: true
                  - id: 50006
                    table_name: AD_Org
                    values:
                      KeyColumn: 50006
                      DisplayColumn: Store West
                      UUID: 51748134-e4f9-4d19-b568-77fe15b75887
                    is_active: true
                next_page_token: ''