openapi: 3.0.0
info:
  title: Time_control
  version: 1.0.0
servers:
  - url: http://{{host}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /time-control/assignements:
    post:
      tags:
        - default
      summary: CreateResourceAssignment
      description: >-
        **Endpoint**: POST /Time_control


        **Description**: Returns ResourceAssignment


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/time-control/assignements


        **Method**: POST


        **Parameters (Body):**


        - resource_type_id (Int32, Mandatory)

        - name (String, Mandatory)

        - description (String, optional)
            

        **Application Example**


        ``` bash

        curl --location 'http://api.adempiere.io/time-control/assignements' \

        --header 'Content-Type: application/json' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE3MTA1MTA0MDEsImV4cCI6MTcxMDU5NjgwMX0.nYQbrcT9RyHNRCf-oNM50ZVSO6uJ9gvrQQ7e0fzU9Ik'
        \

        --data '{
            "resource_type_id":100,
            "name":"Consultant",
            "description":"prueba"
        }'

         ```

        **Example Answer**


        ``` json

        {
            "id": 1000000,
            "resource": {
                "id": 100,
                "resource_type": {
                    "id": 100,
                    "value": "Consultant",
                    "name": "Consultant",
                    "description": "",
                    "unit_of_measure": {
                        "id": 101,
                        "code": "HR",
                        "symbol": "h  ",
                        "name": "Hora",
                        "description": "",
                        "standard_precision": 2,
                        "costing_precision": 2
                    }
                },
                "name": "Mary Consultant"
            },
            "name": "Consultant",
            "description": "",
            "assign_date_from": "2024-03-07T18:37:08Z",
            "is_confirmed": false,
            "quantity": "0"
        }

         ```

        **Common mistakes**


        - there is no data
            

        ``` json

        {
            "code": 13,
            "message": "Organization",
            "details": []
        }

         ```

        - the name is missing
            

        ``` json

        {
            "code": 13,
            "message": "Fill mandatory fields:  &Name",
            "details": []
        }

         ```

        - resource type id missing
            

        ``` json

        {
            "code": 13,
            "message": "Fill mandatory fields:  Resource Type",
            "details": []
        }

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                resource_type_id: 100
                name: Consultant
                description: prueba
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 18:37:08 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '504'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '99'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                id: 1000000
                resource:
                  id: 100
                  resource_type:
                    id: 100
                    value: Consultant
                    name: Consultant
                    description: ''
                    unit_of_measure:
                      id: 101
                      code: HR
                      symbol: 'h  '
                      name: Hora
                      description: ''
                      standard_precision: 2
                      costing_precision: 2
                  name: Mary Consultant
                name: Consultant
                description: ''
                assign_date_from: '2024-03-07T18:37:08Z'
                is_confirmed: false
                quantity: '0'
    get:
      tags:
        - default
      summary: ListResourcesAssignment
      description: >-
        **Endpoint**: GET /Time_control


        **Description**: Returns ListResourcesAssignment


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/time-control/assignements


        **Method**: GET


        **Application Example**


        ``` bash

        curl --location 'http://api.adempiere.io/time-control/assignements' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE3MTA1MTA0MDEsImV4cCI6MTcxMDU5NjgwMX0.nYQbrcT9RyHNRCf-oNM50ZVSO6uJ9gvrQQ7e0fzU9Ik'

         ```

        **Example Answer**


        ``` json

        {
            "record_count": "2",
            "records": [
                {
                    "id": 100,
                    "resource": {
                        "id": 100,
                        "resource_type": {
                            "id": 100,
                            "value": "Consultant",
                            "name": "Consultant",
                            "description": "",
                            "unit_of_measure": {
                                "id": 101,
                                "code": "HR",
                                "symbol": "h  ",
                                "name": "Hora",
                                "description": "",
                                "standard_precision": 2,
                                "costing_precision": 2
                            }
                        },
                        "name": "Mary Consultant"
                    },
                    "name": "Garden Layout",
                    "description": "Initial Discussion",
                    "assign_date_from": "2003-02-05T14:00:00Z",
                    "assign_date_to": "2003-02-05T17:00:00Z",
                    "is_confirmed": false,
                    "quantity": "3"
                },
                {
                    "id": 101,
                    "resource": {
                        "id": 100,
                        "resource_type": {
                            "id": 100,
                            "value": "Consultant",
                            "name": "Consultant",
                            "description": "",
                            "unit_of_measure": {
                                "id": 101,
                                "code": "HR",
                                "symbol": "h  ",
                                "name": "Hora",
                                "description": "",
                                "standard_precision": 2,
                                "costing_precision": 2
                            }
                        },
                        "name": "Mary Consultant"
                    },
                    "name": "Garden Layout",
                    "description": "Discuss Budget",
                    "assign_date_from": "2003-02-05T21:00:00Z",
                    "assign_date_to": "2003-02-05T22:00:00Z",
                    "is_confirmed": false,
                    "quantity": "1"
                }
            ],
            "next_page_token": ""
        }

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 18:36:39 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '1304'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '162'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '2'
                records:
                  - id: 100
                    resource:
                      id: 100
                      resource_type:
                        id: 100
                        value: Consultant
                        name: Consultant
                        description: ''
                        unit_of_measure:
                          id: 101
                          code: HR
                          symbol: 'h  '
                          name: Hora
                          description: ''
                          standard_precision: 2
                          costing_precision: 2
                      name: Mary Consultant
                    name: Garden Layout
                    description: Initial Discussion
                    assign_date_from: '2003-02-05T14:00:00Z'
                    assign_date_to: '2003-02-05T17:00:00Z'
                    is_confirmed: false
                    quantity: '3'
                  - id: 101
                    resource:
                      id: 100
                      resource_type:
                        id: 100
                        value: Consultant
                        name: Consultant
                        description: ''
                        unit_of_measure:
                          id: 101
                          code: HR
                          symbol: 'h  '
                          name: Hora
                          description: ''
                          standard_precision: 2
                          costing_precision: 2
                      name: Mary Consultant
                    name: Garden Layout
                    description: Discuss Budget
                    assign_date_from: '2003-02-05T21:00:00Z'
                    assign_date_to: '2003-02-05T22:00:00Z'
                    is_confirmed: false
                    quantity: '1'
                next_page_token: ''
  /time-control/assignements/{id}:
    put:
      tags:
        - default
      summary: UpdateResourceAssignment
      description: >-
        **Endpoint**: GET /Payment


        **Description**: Returns ResourceAssignment


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/time-control/assignements/{id}


        **Method**: GET


        **Parameters (Params)**


        id (Int32, Mandatory)


        **Parameters (Body)**


        name (String, optional)


        description (String, optional)


        **Application Example**


        ``` bash

        curl --location --request PUT
        'http://api.adempiere.io/time-control/assignements/1000001/confirm' \

        --header 'Content-Type: application/json' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE3MTA1MTA0MDEsImV4cCI6MTcxMDU5NjgwMX0.nYQbrcT9RyHNRCf-oNM50ZVSO6uJ9gvrQQ7e0fzU9Ik'
        \

        --data '{
            "name":"qwe",
            "description":"prueba"
        }'

         ```

        **Example Answer**


        ``` json

        {
            "id": 100,
            "resource": {
                "id": 100,
                "resource_type": {
                    "id": 100,
                    "value": "Consultant",
                    "name": "Consultant",
                    "description": "",
                    "unit_of_measure": {
                        "id": 101,
                        "code": "HR",
                        "symbol": "h  ",
                        "name": "Hora",
                        "description": "",
                        "standard_precision": 2,
                        "costing_precision": 2
                    }
                },
                "name": "Mary Consultant"
            },
            "name": "qwe",
            "description": "",
            "assign_date_from": "2003-02-05T14:00:00Z",
            "assign_date_to": "2003-02-05T17:00:00Z",
            "is_confirmed": false,
            "quantity": "3"
        }

         ```

        **Common mistakes**


        - the resource is not active or not found
            

        ``` json

        {
            "code": 13,
            "message": "Resource is not available or not active",
            "details": []
        }

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: qwe
                description: prueba
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1000001'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 18:39:07 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '536'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '108'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                id: 100
                resource:
                  id: 100
                  resource_type:
                    id: 100
                    value: Consultant
                    name: Consultant
                    description: ''
                    unit_of_measure:
                      id: 101
                      code: HR
                      symbol: 'h  '
                      name: Hora
                      description: ''
                      standard_precision: 2
                      costing_precision: 2
                  name: Mary Consultant
                name: qwe
                description: ''
                assign_date_from: '2003-02-05T14:00:00Z'
                assign_date_to: '2003-02-05T17:00:00Z'
                is_confirmed: false
                quantity: '3'
    delete:
      tags:
        - default
      summary: DeleteResourceAssignment
      description: >-
        **Endpoint**: DELETE /Payment


        **Description**: Returns Empty


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/info/open-items/payments


        **Method**: DELETE


        **Parameters (Params):**


        id (Int32, Mandatory)


        **Application Example**


        ``` bash

        curl --location --request DELETE
        'http://api.adempiere.io/time-control/assignements/1000001' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE3MTA1MTA0MDEsImV4cCI6MTcxMDU5NjgwMX0.nYQbrcT9RyHNRCf-oNM50ZVSO6uJ9gvrQQ7e0fzU9Ik'
        \

        --data ''

         ```

        **Example Answer**


        ``` json

        {}

         ```

        **Common mistakes**


        - the resource is not active or not found
            

        ``` json

        {
            "code": 13,
            "message": "Resource is not available or not active",
            "details": []
        }

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1000001'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 18:41:02 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '3'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '123'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example: {}
  /time-control/assignements/{id}/confirm:
    post:
      tags:
        - default
      summary: ConfirmResourceAssignment
      description: >-
        **Endpoint**: POST /Time_control


        **Description**: Returns ResourceAssignment


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/time-control/assignements/{id}/confirm


        **Method**: POST


        **Parameters (Params):**


        id (Int32,Mandatory)


        **Application Example**


        ``` bash

        curl --location --request POST
        'http://api.adempiere.io/time-control/assignements/1000002/confirm' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE3MTA1MTA0MDEsImV4cCI6MTcxMDU5NjgwMX0.nYQbrcT9RyHNRCf-oNM50ZVSO6uJ9gvrQQ7e0fzU9Ik'

         ```

        **Example Answer**


        ``` json

        {
            "id": 1000002,
            "resource": {
                "id": 100,
                "resource_type": {
                    "id": 100,
                    "value": "Consultant",
                    "name": "Consultant",
                    "description": "",
                    "unit_of_measure": {
                        "id": 101,
                        "code": "HR",
                        "symbol": "h  ",
                        "name": "Hora",
                        "description": "",
                        "standard_precision": 2,
                        "costing_precision": 2
                    }
                },
                "name": "Mary Consultant"
            },
            "name": "Consultant",
            "description": "",
            "assign_date_from": "2024-03-07T18:42:31Z",
            "assign_date_to": "2024-03-07T18:42:48.278Z",
            "is_confirmed": true,
            "quantity": "0.00"
        }

         ```

        **Common mistakes**


        - the resource is not found
            

        ``` json

        {
            "code": 13,
            "message": "Resource Assignment * Not found *",
            "details": []
        }

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1000002'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 18:42:48 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '553'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '130'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                id: 1000002
                resource:
                  id: 100
                  resource_type:
                    id: 100
                    value: Consultant
                    name: Consultant
                    description: ''
                    unit_of_measure:
                      id: 101
                      code: HR
                      symbol: 'h  '
                      name: Hora
                      description: ''
                      standard_precision: 2
                      costing_precision: 2
                  name: Mary Consultant
                name: Consultant
                description: ''
                assign_date_from: '2024-03-07T18:42:31Z'
                assign_date_to: '2024-03-07T18:42:48.278Z'
                is_confirmed: true
                quantity: '0.00'
