openapi: 3.0.0
info:
  title: Trial_balance_drillable
  version: 1.0.0
servers:
  - url: http://{{host}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /trial-balance-drillable/organizations:
    get:
      tags:
        - default
      summary: ListOrganizations
      description: >-
        **Endpoint**: GET /trial_balance_drillable


        **Description**: Returns ListLookupItems


        **Full** **URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/trial-balance-drillable/organizations


        **Method**: GET


        **Application Example:**


        ``` bash

        curl --location
        'http://api.adempiere.io/trial-balance-drillable/organizations' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ2IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE3MTA2Mjg3ODAsImV4cCI6MTcxMDcxNTE4MH0.8Sg48hnxmTbqs7nG_JoafC7AwXbHX3jWAPLPJ0Qo7VU'

         ```

        **Answer Example:**


        ``` json

        {
            "record_count": "9",
            "records": [
                {
                    "id": 50001,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 50001,
                        "DisplayColumn": "Fertilizer-Fertilizer",
                        "UUID": "5bdf61e6-18d5-491e-8826-ae7a9557e635"
                    },
                    "is_active": true
                },
                {
                    "id": 50000,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 50000,
                        "DisplayColumn": "Furniture-Furniture",
                        "UUID": "803a37b7-0cee-4411-99aa-d3b328dec3b1"
                    },
                    "is_active": true
                },
                {
                    "id": 11,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 11,
                        "DisplayColumn": "HQ-HQ",
                        "UUID": "08c224db-bb86-4306-9fa5-ba1dfd34b693"
                    },
                    "is_active": true
                },
                {
                    "id": 12,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 12,
                        "DisplayColumn": "Store Central-Store Central",
                        "UUID": "6a0e31b1-2ade-4f8e-a907-ed63ab29fc0d"
                    },
                    "is_active": true
                },
                {
                    "id": 50005,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 50005,
                        "DisplayColumn": "Store East-Store East",
                        "UUID": "818cfb05-f9db-4a1c-853f-7b3f2b35337a"
                    },
                    "is_active": true
                },
                {
                    "id": 50002,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 50002,
                        "DisplayColumn": "Store North-Store North",
                        "UUID": "06e23570-6653-4b3c-a921-6c54732b02a9"
                    },
                    "is_active": true
                },
                {
                    "id": 50004,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 50004,
                        "DisplayColumn": "Store South-Store South",
                        "UUID": "cf2ac4a7-0718-4f69-a042-bb8fcb85e9da"
                    },
                    "is_active": true
                },
                {
                    "id": 50007,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 50007,
                        "DisplayColumn": "Stores-Stores",
                        "UUID": "bc3ab10e-a9d3-4941-b29f-da0c5f76b7c6"
                    },
                    "is_active": true
                },
                {
                    "id": 50006,
                    "table_name": "AD_Org",
                    "values": {
                        "KeyColumn": 50006,
                        "DisplayColumn": "Store West-Store West",
                        "UUID": "51748134-e4f9-4d19-b568-77fe15b75887"
                    },
                    "is_active": true
                }
            ],
            "next_page_token": ""
        }

         ```

        **Change control**


        | **Version** | Date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 18:53:02 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '1973'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '112'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '9'
                records:
                  - id: 50001
                    table_name: AD_Org
                    values:
                      KeyColumn: 50001
                      DisplayColumn: Fertilizer-Fertilizer
                      UUID: 5bdf61e6-18d5-491e-8826-ae7a9557e635
                    is_active: true
                  - id: 50000
                    table_name: AD_Org
                    values:
                      KeyColumn: 50000
                      DisplayColumn: Furniture-Furniture
                      UUID: 803a37b7-0cee-4411-99aa-d3b328dec3b1
                    is_active: true
                  - id: 11
                    table_name: AD_Org
                    values:
                      KeyColumn: 11
                      DisplayColumn: HQ-HQ
                      UUID: 08c224db-bb86-4306-9fa5-ba1dfd34b693
                    is_active: true
                  - id: 12
                    table_name: AD_Org
                    values:
                      KeyColumn: 12
                      DisplayColumn: Store Central-Store Central
                      UUID: 6a0e31b1-2ade-4f8e-a907-ed63ab29fc0d
                    is_active: true
                  - id: 50005
                    table_name: AD_Org
                    values:
                      KeyColumn: 50005
                      DisplayColumn: Store East-Store East
                      UUID: 818cfb05-f9db-4a1c-853f-7b3f2b35337a
                    is_active: true
                  - id: 50002
                    table_name: AD_Org
                    values:
                      KeyColumn: 50002
                      DisplayColumn: Store North-Store North
                      UUID: 06e23570-6653-4b3c-a921-6c54732b02a9
                    is_active: true
                  - id: 50004
                    table_name: AD_Org
                    values:
                      KeyColumn: 50004
                      DisplayColumn: Store South-Store South
                      UUID: cf2ac4a7-0718-4f69-a042-bb8fcb85e9da
                    is_active: true
                  - id: 50007
                    table_name: AD_Org
                    values:
                      KeyColumn: 50007
                      DisplayColumn: Stores-Stores
                      UUID: bc3ab10e-a9d3-4941-b29f-da0c5f76b7c6
                    is_active: true
                  - id: 50006
                    table_name: AD_Org
                    values:
                      KeyColumn: 50006
                      DisplayColumn: Store West-Store West
                      UUID: 51748134-e4f9-4d19-b568-77fe15b75887
                    is_active: true
                next_page_token: ''
  /trial-balance-drillable/budgets:
    get:
      tags:
        - default
      summary: ListBudgets
      description: >-
        **Endpoint**: GET /trial_balance_drillable


        **Description**: Returns ListLookupItems


        **Full** **URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/trial-balance-drillable/budgets


        **Method**: GET


        **Application Example:**


        ``` bash

        curl --location
        'http://api.adempiere.io/trial-balance-drillable/budgets' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ2IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE3MTA2Mjg3ODAsImV4cCI6MTcxMDcxNTE4MH0.8Sg48hnxmTbqs7nG_JoafC7AwXbHX3jWAPLPJ0Qo7VU'

         ```

        **Answer Example:**


        ``` json

        {
            "record_count": "1",
            "records": [
                {
                    "id": 100,
                    "table_name": "GL_Budget",
                    "values": {
                        "KeyColumn": 100,
                        "DisplayColumn": "Target Budget",
                        "UUID": "5bbb1369-b26a-4e18-8a1e-e8df04f01c95"
                    },
                    "is_active": true
                }
            ],
            "next_page_token": ""
        }

         ```

        **Change control**


        | **Version** | Date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 18:53:28 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '272'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '113'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '1'
                records:
                  - id: 100
                    table_name: GL_Budget
                    values:
                      KeyColumn: 100
                      DisplayColumn: Target Budget
                      UUID: 5bbb1369-b26a-4e18-8a1e-e8df04f01c95
                    is_active: true
                next_page_token: ''
  /trial-balance-drillable/periods:
    get:
      tags:
        - default
      summary: ListPeriods
      description: >-
        **Endpoint**: GET /trial_balance_drillable


        **Description**: Returns ListLookupItems


        **Full** **URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/trial-balance-drillable/periods


        **Method**: GET


        **Application Example:**


        ``` bash

        curl --location
        'http://api.adempiere.io/trial-balance-drillable/periods' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ2IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE3MTA2Mjg3ODAsImV4cCI6MTcxMDcxNTE4MH0.8Sg48hnxmTbqs7nG_JoafC7AwXbHX3jWAPLPJ0Qo7VU'

         ```

        **Answer Example:**


        ``` json

        {
            "record_count": "1",
            "records": [
                {
                    "id": 100,
                    "table_name": "GL_Budget",
                    "values": {
                        "KeyColumn": 100,
                        "DisplayColumn": "Target Budget",
                        "UUID": "5bbb1369-b26a-4e18-8a1e-e8df04f01c95"
                    },
                    "is_active": true
                }
            ],
            "next_page_token": ""
        }

         ```

        **Change control**


        | **Version** | Date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 18:55:04 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '10056'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '103'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '168'
                records:
                  - id: 136
                    table_name: C_Period
                    values:
                      KeyColumn: 136
                      DisplayColumn: 2021-01
                      UUID: 5ec0683e-bb83-4a57-a2fa-9e8a37c84f79
                    is_active: true
                  - id: 137
                    table_name: C_Period
                    values:
                      KeyColumn: 137
                      DisplayColumn: 2021-02
                      UUID: d0ed54f0-a2c6-45a3-b0f8-cefbd731bd63
                    is_active: true
                  - id: 138
                    table_name: C_Period
                    values:
                      KeyColumn: 138
                      DisplayColumn: 2021-03
                      UUID: 3617154e-c03a-4e5a-b797-fb05c784dab2
                    is_active: true
                  - id: 139
                    table_name: C_Period
                    values:
                      KeyColumn: 139
                      DisplayColumn: 2021-04
                      UUID: 81d25121-0b95-4d16-a49b-83086f4964d6
                    is_active: true
                  - id: 140
                    table_name: C_Period
                    values:
                      KeyColumn: 140
                      DisplayColumn: 2021-05
                      UUID: 797985e9-dd7d-4e53-ba1e-c2748dc99c2d
                    is_active: true
                  - id: 141
                    table_name: C_Period
                    values:
                      KeyColumn: 141
                      DisplayColumn: 2021-06
                      UUID: 3c3bbcf3-c033-49bd-b80c-3c2503983aa2
                    is_active: true
                  - id: 142
                    table_name: C_Period
                    values:
                      KeyColumn: 142
                      DisplayColumn: 2021-07
                      UUID: 4f7268fa-9f59-4eba-9884-6c7217cda4ae
                    is_active: true
                  - id: 143
                    table_name: C_Period
                    values:
                      KeyColumn: 143
                      DisplayColumn: 2021-08
                      UUID: 5a3ad4e8-a02a-4542-af35-b5c151d586c9
                    is_active: true
                  - id: 144
                    table_name: C_Period
                    values:
                      KeyColumn: 144
                      DisplayColumn: 2021-09
                      UUID: 243e9167-8b94-4f22-8608-1795be5a4ee7
                    is_active: true
                  - id: 145
                    table_name: C_Period
                    values:
                      KeyColumn: 145
                      DisplayColumn: 2021-10
                      UUID: 90914a98-d7b1-4440-9fc2-42358286d123
                    is_active: true
                  - id: 146
                    table_name: C_Period
                    values:
                      KeyColumn: 146
                      DisplayColumn: 2021-11
                      UUID: 9cc7792a-3e0b-4a1f-9360-4b14a4da698c
                    is_active: true
                  - id: 147
                    table_name: C_Period
                    values:
                      KeyColumn: 147
                      DisplayColumn: 2021-12
                      UUID: b82ab782-8e72-4aa3-9177-4d9ac65e3a44
                    is_active: true
                  - id: 148
                    table_name: C_Period
                    values:
                      KeyColumn: 148
                      DisplayColumn: 2022-01
                      UUID: 28a4856b-7207-4081-b573-48c718e56d95
                    is_active: true
                  - id: 149
                    table_name: C_Period
                    values:
                      KeyColumn: 149
                      DisplayColumn: 2022-02
                      UUID: dc0ce891-61ba-479b-bbf3-d9646f8b466e
                    is_active: true
                  - id: 150
                    table_name: C_Period
                    values:
                      KeyColumn: 150
                      DisplayColumn: 2022-03
                      UUID: 56c6821f-69f4-4eb1-a5dc-8c8a1fe6b507
                    is_active: true
                  - id: 151
                    table_name: C_Period
                    values:
                      KeyColumn: 151
                      DisplayColumn: 2022-04
                      UUID: 238049d8-ee4e-4452-8351-9df64873ddfc
                    is_active: true
                  - id: 152
                    table_name: C_Period
                    values:
                      KeyColumn: 152
                      DisplayColumn: 2022-05
                      UUID: 3ad3adbd-7a89-4c35-b17c-1a726c0bf1af
                    is_active: true
                  - id: 153
                    table_name: C_Period
                    values:
                      KeyColumn: 153
                      DisplayColumn: 2022-06
                      UUID: 2e65e102-56a9-4130-b7f2-0f205ad2793b
                    is_active: true
                  - id: 154
                    table_name: C_Period
                    values:
                      KeyColumn: 154
                      DisplayColumn: 2022-07
                      UUID: de74e7cd-eb4e-4318-bf21-d9432e722df1
                    is_active: true
                  - id: 155
                    table_name: C_Period
                    values:
                      KeyColumn: 155
                      DisplayColumn: 2022-08
                      UUID: 9d42da58-fa02-4427-a017-cfd028827ba4
                    is_active: true
                  - id: 156
                    table_name: C_Period
                    values:
                      KeyColumn: 156
                      DisplayColumn: 2022-09
                      UUID: 4d1f50fc-7694-431a-8d56-ca305ceb775a
                    is_active: true
                  - id: 157
                    table_name: C_Period
                    values:
                      KeyColumn: 157
                      DisplayColumn: 2022-10
                      UUID: 7ed8d1b0-29e2-4e22-a405-c1d39b6b8c00
                    is_active: true
                  - id: 158
                    table_name: C_Period
                    values:
                      KeyColumn: 158
                      DisplayColumn: 2022-11
                      UUID: 3548390f-7f6a-4c34-ad3a-1c71f6a5465b
                    is_active: true
                  - id: 159
                    table_name: C_Period
                    values:
                      KeyColumn: 159
                      DisplayColumn: 2022-12
                      UUID: 4e1b5334-38b8-48f3-931b-97b6447cca70
                    is_active: true
                  - id: 160
                    table_name: C_Period
                    values:
                      KeyColumn: 160
                      DisplayColumn: 2023-01
                      UUID: 43a0594f-2b57-4289-a57f-a98728431132
                    is_active: true
                  - id: 161
                    table_name: C_Period
                    values:
                      KeyColumn: 161
                      DisplayColumn: 2023-02
                      UUID: 220b6e66-3ebd-446b-ab9e-7d9f9bf7c228
                    is_active: true
                  - id: 162
                    table_name: C_Period
                    values:
                      KeyColumn: 162
                      DisplayColumn: 2023-03
                      UUID: 6c8c4446-93e6-4f88-8048-bd55c2df604d
                    is_active: true
                  - id: 163
                    table_name: C_Period
                    values:
                      KeyColumn: 163
                      DisplayColumn: 2023-04
                      UUID: 23215074-6b3a-4dbd-9643-0f4f5f10a89f
                    is_active: true
                  - id: 164
                    table_name: C_Period
                    values:
                      KeyColumn: 164
                      DisplayColumn: 2023-05
                      UUID: ebad9524-8b3a-4da5-9d88-64439df3a7da
                    is_active: true
                  - id: 165
                    table_name: C_Period
                    values:
                      KeyColumn: 165
                      DisplayColumn: 2023-06
                      UUID: eee723af-208e-4b62-85b6-6a36964e6d63
                    is_active: true
                  - id: 166
                    table_name: C_Period
                    values:
                      KeyColumn: 166
                      DisplayColumn: 2023-07
                      UUID: 55d8d014-098f-48f7-b7de-d8edf6816e8c
                    is_active: true
                  - id: 167
                    table_name: C_Period
                    values:
                      KeyColumn: 167
                      DisplayColumn: 2023-08
                      UUID: 93901a3a-0e94-47e0-835c-296f1de0310e
                    is_active: true
                  - id: 168
                    table_name: C_Period
                    values:
                      KeyColumn: 168
                      DisplayColumn: 2023-09
                      UUID: 92db937f-3ab0-4de9-8a64-2ef82b86690f
                    is_active: true
                  - id: 169
                    table_name: C_Period
                    values:
                      KeyColumn: 169
                      DisplayColumn: 2023-10
                      UUID: 39da29a1-99a5-47a1-a51a-aa498ce17a55
                    is_active: true
                  - id: 170
                    table_name: C_Period
                    values:
                      KeyColumn: 170
                      DisplayColumn: 2023-11
                      UUID: 39499342-87e7-49ca-97c4-c83a56110127
                    is_active: true
                  - id: 171
                    table_name: C_Period
                    values:
                      KeyColumn: 171
                      DisplayColumn: 2023-12
                      UUID: 4c19c662-b9d4-45a4-bd52-9a5c310df5fc
                    is_active: true
                  - id: 172
                    table_name: C_Period
                    values:
                      KeyColumn: 172
                      DisplayColumn: 2024-01
                      UUID: d4fceb9b-b449-46ed-9114-bad1e433ba62
                    is_active: true
                  - id: 173
                    table_name: C_Period
                    values:
                      KeyColumn: 173
                      DisplayColumn: 2024-02
                      UUID: 537e65bd-e687-4455-87e8-b712b6ee9d8b
                    is_active: true
                  - id: 174
                    table_name: C_Period
                    values:
                      KeyColumn: 174
                      DisplayColumn: 2024-03
                      UUID: 9aa26b43-b285-4952-b83f-5ecb4abfad58
                    is_active: true
                  - id: 175
                    table_name: C_Period
                    values:
                      KeyColumn: 175
                      DisplayColumn: 2024-04
                      UUID: 1d21d5e7-d2f4-4808-9ff6-708a230c65bf
                    is_active: true
                  - id: 176
                    table_name: C_Period
                    values:
                      KeyColumn: 176
                      DisplayColumn: 2024-05
                      UUID: 68d14f3c-22da-4c28-b212-dd40aba76c05
                    is_active: true
                  - id: 177
                    table_name: C_Period
                    values:
                      KeyColumn: 177
                      DisplayColumn: 2024-06
                      UUID: 7df078d5-67b2-4dcc-ae41-d5e8a87ce44c
                    is_active: true
                  - id: 178
                    table_name: C_Period
                    values:
                      KeyColumn: 178
                      DisplayColumn: 2024-07
                      UUID: 13fe65bb-e178-4eb6-860c-db0466a45b37
                    is_active: true
                  - id: 179
                    table_name: C_Period
                    values:
                      KeyColumn: 179
                      DisplayColumn: 2024-08
                      UUID: c14f6d0c-9cd3-483e-b973-9ce888e5110b
                    is_active: true
                  - id: 180
                    table_name: C_Period
                    values:
                      KeyColumn: 180
                      DisplayColumn: 2024-09
                      UUID: a615fc6a-4d00-4719-ba6d-870b39b097cc
                    is_active: true
                  - id: 181
                    table_name: C_Period
                    values:
                      KeyColumn: 181
                      DisplayColumn: 2024-10
                      UUID: 325a63b1-585d-47ff-9034-2684480bf445
                    is_active: true
                  - id: 182
                    table_name: C_Period
                    values:
                      KeyColumn: 182
                      DisplayColumn: 2024-11
                      UUID: d2d6f4c6-0528-4df0-bd1f-44c6f9dffc31
                    is_active: true
                  - id: 183
                    table_name: C_Period
                    values:
                      KeyColumn: 183
                      DisplayColumn: 2024-12
                      UUID: 705e788d-7cbb-4e6a-939c-f122e8b5a6db
                    is_active: true
                  - id: 184
                    table_name: C_Period
                    values:
                      KeyColumn: 184
                      DisplayColumn: 2025-01
                      UUID: 0d429724-e804-4dd9-ac3b-e1cab71c2bc4
                    is_active: true
                  - id: 185
                    table_name: C_Period
                    values:
                      KeyColumn: 185
                      DisplayColumn: 2025-02
                      UUID: 43e76f1c-c43a-4c9d-a21f-6fb05dd40b3d
                    is_active: true
                next_page_token: c2d6e690-b810-4593-bdb7-f3b0f9b7331c-2
  /trial-balance-drillable/accouting-keys:
    get:
      tags:
        - default
      summary: ListAccoutingKeys
      description: >-
        **Endpoint**: GET /trial_balance_drillable


        **Description**: Returns ListLookupItems


        **Full** **URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/trial-balance-drillable/accouting-keys


        **Method**: GET


        **Application Example:**


        ``` bash

        curl --location
        'http://api.adempiere.io/trial-balance-drillable/accouting-keys' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ2IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE3MTA2Mjg3ODAsImV4cCI6MTcxMDcxNTE4MH0.8Sg48hnxmTbqs7nG_JoafC7AwXbHX3jWAPLPJ0Qo7VU'

         ```

        **Answer Example:**


        ``` json

        {
                    "id": 508,
                    "table_name": "C_ElementValue",
                    "values": {
                        "KeyColumn": 508,
                        "DisplayColumn": "11100_Checking Account",
                        "UUID": "104ec46f-0296-45ac-ace7-597b968a7c1e"
                    },
                    "is_active": true
                },

         ```

        **Change control**


        | **Version** | Date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 18:55:38 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '11385'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '117'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '382'
                records:
                  - id: 508
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 508
                      DisplayColumn: 11100_Checking Account
                      UUID: 104ec46f-0296-45ac-ace7-597b968a7c1e
                    is_active: true
                  - id: 509
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 509
                      DisplayColumn: 11110_Checking In-Transfer
                      UUID: 0cf6e4dd-739c-46d7-b444-d3945a41945b
                    is_active: true
                  - id: 510
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 510
                      DisplayColumn: 11120_Checking Unidentified Receipts
                      UUID: 34abc879-66dd-42b1-a0e0-6f67a5eff555
                    is_active: true
                  - id: 511
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 511
                      DisplayColumn: 11130_Checking Unallocated Receipts
                      UUID: df119190-0190-42c2-b6a0-256dfffba790
                    is_active: true
                  - id: 512
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 512
                      DisplayColumn: 11200_Checking Account 2
                      UUID: d2b937f6-8543-4305-827a-5ea51232d208
                    is_active: true
                  - id: 513
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 513
                      DisplayColumn: 11300_Savings Account
                      UUID: 63f58b3b-c39b-4beb-b4d9-b8f707092264
                    is_active: true
                  - id: 514
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 514
                      DisplayColumn: 11800_Cash in Registers
                      UUID: 7f78a131-8736-48df-b759-0408a3e4c259
                    is_active: true
                  - id: 50021
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 50021
                      DisplayColumn: 11810_Cash for Store Central
                      UUID: 950b1cd3-6c49-42ac-896e-fcd15c673bad
                    is_active: true
                  - id: 50023
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 50023
                      DisplayColumn: 11820_Cash for Store Central In-Transfer
                      UUID: 6c59bf40-6f68-4fa2-a13e-c4428335f860
                    is_active: true
                  - id: 50024
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 50024
                      DisplayColumn: 11830_Safe for Store Central
                      UUID: be318b7c-c7b0-4161-b3a0-10c3e352f254
                    is_active: true
                  - id: 50025
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 50025
                      DisplayColumn: 11840_Safe In-Transfer for Store Central
                      UUID: 109a571c-fb4b-4632-9060-6b70dabf954b
                    is_active: true
                  - id: 515
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 515
                      DisplayColumn: 11900_Petty Cash
                      UUID: f9268b28-6beb-4b16-88f1-fc9a87bc8cd6
                    is_active: true
                  - id: 516
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 516
                      DisplayColumn: 11910_Petty Cash In-Transfer
                      UUID: a904e847-2680-4a24-b331-0a5917c0c77e
                    is_active: true
                  - id: 507
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 507
                      DisplayColumn: 11_Cash
                      UUID: e5092b80-8985-4ea6-95c3-bcee287c7000
                    is_active: true
                  - id: 518
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 518
                      DisplayColumn: 12110_Accounts Receivable - Trade
                      UUID: 86437100-5a54-4ec2-bc2c-3620cab7773e
                    is_active: true
                  - id: 782
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 782
                      DisplayColumn: 12115_Accounts Receivable Services - Trade
                      UUID: 71aa28f1-27ac-44cd-ad9b-9f1d71f7cf87
                    is_active: true
                  - id: 519
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 519
                      DisplayColumn: 12120_A/R Non Sufficient Funds Returned Checks
                      UUID: 42b593be-57c3-4084-8de3-018e33797c06
                    is_active: true
                  - id: 520
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 520
                      DisplayColumn: 12180_A/R Trade Allowance for Bad Debit
                      UUID: 01cdedaa-c151-4c6b-b717-6160da88f2e5
                    is_active: true
                  - id: 521
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 521
                      DisplayColumn: 12190_Not invoiced receivables
                      UUID: 7132d16b-0a15-4123-a1f1-6b5e50bb95a9
                    is_active: true
                  - id: 774
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 774
                      DisplayColumn: 121_Accounts Receivable - Trade
                      UUID: 6b8eb6cb-c060-419e-bdba-cca173535c62
                    is_active: true
                  - id: 523
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 523
                      DisplayColumn: 12210_In Transit A/R Amex
                      UUID: 4e396a43-2ec6-4b66-8ee8-772bb6bc13b9
                    is_active: true
                  - id: 524
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 524
                      DisplayColumn: 12220_In Transit A/R Master Card
                      UUID: 38c2a8f2-9df4-4b85-abec-ec2cecf8ecbd
                    is_active: true
                  - id: 525
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 525
                      DisplayColumn: 12230_In Transit A/R Visa
                      UUID: 51710d19-a44b-41b8-8460-f23c96ac375e
                    is_active: true
                  - id: 738
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 738
                      DisplayColumn: 12240_In Transit A/R ATM Cards
                      UUID: 0594d379-a67e-42e2-8072-d15ee1850588
                    is_active: true
                  - id: 526
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 526
                      DisplayColumn: 12290_A/R Credit Cards Allowance for Bad Debit
                      UUID: b1d8342e-7e01-4cbb-86d5-2494434791da
                    is_active: true
                  - id: 522
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 522
                      DisplayColumn: 122_Credit Card in Transit
                      UUID: 261663aa-350a-4ed6-8fac-55ce9a904777
                    is_active: true
                  - id: 527
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 527
                      DisplayColumn: 12300_Vendor Allowances Receivable
                      UUID: 7d04ffd7-895b-48cd-ada5-19820bdf3a32
                    is_active: true
                  - id: 529
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 529
                      DisplayColumn: 12410_Loans Receivable Employees
                      UUID: fd4a8a00-0d48-4514-aac5-37fe90928756
                    is_active: true
                  - id: 739
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 739
                      DisplayColumn: 12420_Loans Receivable Owners/Shareholders
                      UUID: 838be2b7-7f8c-40e0-8dfc-29a2c1bb82c7
                    is_active: true
                  - id: 530
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 530
                      DisplayColumn: 12440_Loans Receivable Others
                      UUID: b0adb67c-2d94-4578-8211-917e2d6d8678
                    is_active: true
                  - id: 528
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 528
                      DisplayColumn: 124_Loans Receivable
                      UUID: 572e56d1-577f-43fa-9372-5ceb37cd93ba
                    is_active: true
                  - id: 532
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 532
                      DisplayColumn: 12510_Vendor prepayment
                      UUID: 2cc7b178-d6cf-47e9-a778-deef39e64917
                    is_active: true
                  - id: 533
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 533
                      DisplayColumn: 12520_Employee Expense Prepayment
                      UUID: d6078650-c2dc-4ee1-98e1-387cac19161e
                    is_active: true
                  - id: 531
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 531
                      DisplayColumn: 125_Prepayments
                      UUID: d7aac693-2340-4644-b471-ce1b8720137d
                    is_active: true
                  - id: 534
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 534
                      DisplayColumn: 12610_Tax credit A/R
                      UUID: 82f712a2-c490-42ad-b161-dd1d101cc540
                    is_active: true
                  - id: 535
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 535
                      DisplayColumn: 12620_Tax receivables
                      UUID: 4cb06fd0-e711-47d1-b8b3-eb556856eeff
                    is_active: true
                  - id: 740
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 740
                      DisplayColumn: 126_Tax receivables
                      UUID: 3b33f6a1-14b0-4c4e-a0d0-dda21a85b068
                    is_active: true
                  - id: 741
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 741
                      DisplayColumn: 12800_Intercompany Due From
                      UUID: dd7bfbf9-a5d8-4433-a252-e2b3a05d7edc
                    is_active: true
                  - id: 536
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 536
                      DisplayColumn: 12900_A/R Miscellaneous
                      UUID: 6cc4f641-e3a0-4e5e-b7bf-869b45fca276
                    is_active: true
                  - id: 517
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 517
                      DisplayColumn: 12_Accounts Receivable
                      UUID: cd359baf-ceaa-4a18-8c3d-615c8da967c1
                    is_active: true
                  - id: 538
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 538
                      DisplayColumn: 13100_US Government Obligations
                      UUID: 30fa008e-ba17-4af1-9d5c-f9008489697e
                    is_active: true
                  - id: 539
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 539
                      DisplayColumn: 13200_Tax-Exempt Securities
                      UUID: 6d779f71-84a0-4c19-97e5-ccc79e1f68eb
                    is_active: true
                  - id: 540
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 540
                      DisplayColumn: 13300_Other Investments
                      UUID: cac5f71f-e3f2-4ce2-8508-7e225b49171f
                    is_active: true
                  - id: 537
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 537
                      DisplayColumn: 13_Investments
                      UUID: eb4cb2e3-ee92-4f77-a962-a7c9110f61e9
                    is_active: true
                  - id: 776
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 776
                      DisplayColumn: 14100_General Trade Inventory
                      UUID: 4fd56411-1091-48a6-9bb3-6be9ecf2db9d
                    is_active: true
                  - id: 742
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 742
                      DisplayColumn: 14120_Product asset
                      UUID: 8fc780ce-bb2b-441e-8ee4-0ec2a83780bc
                    is_active: true
                  - id: 50005
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 50005
                      DisplayColumn: 14130_Work In Process
                      UUID: e3d90c30-8b98-424d-abb2-9f22e3958a44
                    is_active: true
                  - id: 50006
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 50006
                      DisplayColumn: 14140_Floor Stock
                      UUID: fe875618-5899-4ba8-bff1-a2009b2a1018
                    is_active: true
                  - id: 541
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 541
                      DisplayColumn: 14_Inventory
                      UUID: dc9e0a2b-6099-4aab-aba1-8626b0139212
                    is_active: true
                  - id: 544
                    table_name: C_ElementValue
                    values:
                      KeyColumn: 544
                      DisplayColumn: 15110_Prepaid Insurance
                      UUID: 17c56cdd-e80e-4dac-9f31-ab8304e8a32e
                    is_active: true
                next_page_token: c2d6e690-b810-4593-bdb7-f3b0f9b7331c-2
  /trial-balance-drillable/accouting-fact-summary:
    get:
      tags:
        - default
      summary: ListFactAcctSummary
      description: >-
        **Endpoint**: GET /trial_balance_drillable


        **Description**: Returns ListLookupItems


        **Full** **URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/trial-balance-drillable/accouting-fact-summary/{organization_id}/{period_id}/{report_cube_id}


        **Method**: GET


        **Parameters (Params):**


        - organization_id (Int32, Mandatory)

        - period_id (Int32, Mandatory)

        - report_cube_id (Int32, Mandatory)
            

        **Application Example:**


        ``` bash

        curl --location
        'http://api.adempiere.io/trial-balance-drillable/accouting-fact-summary?organization_id=102&period_id=136&report_cube_id=102'
        \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ2IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE3MTA2Mjg3ODAsImV4cCI6MTcxMDcxNTE4MH0.8Sg48hnxmTbqs7nG_JoafC7AwXbHX3jWAPLPJ0Qo7VU'

         ```

        **Answer Example:**


        ``` json

        {
            "record_count": "1",
            "records": [
                {
                    "id": 631,
                    "value": "32900_",
                    "name": ">>> Prior Year Earnings",
                    "user_list_id": 0,
                    "user_list_name": "",
                    "period_actual_amount": "0",
                    "period_budget_amount": "0",
                    "period_variance_amount": "0",
                    "ytd_actual_amount": "0",
                    "ytd_budget_amount": "0",
                    "variance_amount": "0"
                }
            ],
            "next_page_token": ""
        }

         ```

        **Common mistakes**


        - the period id does not correspond to any of the records
            

        ``` json

        {
            "code": 13,
            "message": "",
            "details": []
        }

         ```

        **Change control**


        | **Version** | Date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      parameters:
        - name: organization_id
          in: query
          schema:
            type: integer
          example: '102'
        - name: period_id
          in: query
          schema:
            type: integer
          example: '136'
        - name: report_cube_id
          in: query
          schema:
            type: integer
          example: '102'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 18:58:58 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '393'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '164'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '1'
                records:
                  - id: 631
                    value: 32900_
                    name: '>>> Prior Year Earnings'
                    user_list_id: 0
                    user_list_name: ''
                    period_actual_amount: '0'
                    period_budget_amount: '0'
                    period_variance_amount: '0'
                    ytd_actual_amount: '0'
                    ytd_budget_amount: '0'
                    variance_amount: '0'
                next_page_token: ''